### ISSUE TITLE
boolean attributes/arguments problem

### ISSUE THREAD

**Issue by stolarczyk** [databio/bed_maker#13]
let's not define `narrowpeak` sample attribute as `TRUE` or `FALSE`, because it's not interpreted correctly as noted in https://github.com/databio/bedmaker/issues/12. Instead let's use `0` and `1` and change the schema accordingly.

**Comment by joseverdezoto** [comment]
@stolarczyk  we shouldn't have problems using `1` or `0` in Python, but apparently `JSON schema` doesn't recognize them as `bool`. It only works with `true` or `false`, which wouldn't be recognized in Python. Would it make sense to just change to a `string` defined as narrow or broad? I like having them as `bool` though

https://json-schema.org/understanding-json-schema/reference/boolean.html

**Comment by stolarczyk** [comment]
> but apparently JSON schema doesn't recognize them as bool

that's correct. It should recognize them as `integer`. And this is how I specified it in the bedmaker schema. Look at the diff linked above your comment.

**Comment by stolarczyk** [comment]
and then the `ArgumentParser`(see `--narrowpeak` argument) in the pipeline casts these values to `bool`

**Comment by xuebingjie1990** [comment]
@stolarczyk resolved?
