### ISSUE TITLE
Failed to generate bigBed file

### ISSUE THREAD

**Issue by xuebingjie1990** [databio/bed_maker#15]
Some bed files have chromosomes that's not  found in the `chrom.sizes` file. Causing the bigBed file generation step to fail.

```
<pre>
chrEBV is not found in chromosome sizes file
</pre>
Command completed. Elapsed time: 0:00:00. Running peak memory: 0.018GB.  
  PID: 19719;	Command: bedToBigBed;	Return code: 255;	Memory used: 0.018GB

Subprocess returned nonzero result. Check above output for details
ERROR: Subprocess returned nonzero result, but pipeline is continuing because nofail=True
Starting cleanup: 3 files; 0 conditional files for cleanup
```

**Comment by nsheff** [comment]
> there are 15,258  (tutorial: 10, encode: 15,248) bigbid files on s3. there should be 17,303 (tutorial: 11, encode: 17,292)

**Comment by xuebingjie1990** [comment]
some bigBed files are not generated correctly, for example: 

```http://data.bedbase.org/bigbed_files/ENCFF293EOZ.bigBed is not a big bed file```
