### ISSUE TITLE
bed to bigBed issue for not standard chromosome naming

### ISSUE THREAD

**Issue by khoroshevskyi** [databio/bed_maker#18]
By executing bedmaker to convert bed to bigBed with unusual (not standard) chromosomes program can't find size of not standard chromosome in chromosome sizes file.

e.g.: "chr22_KI270879v1_alt is not found in chromosome sizes file"

**Comment by nsheff** [comment]
@xuebingjie1990 how did you handle this?

**Comment by xuebingjie1990** [comment]
> By executing bedmaker to convert bed to bigBed with unusual (not standard) chromosomes program can't find size of not standard chromosome in chromosome sizes file.
> 
> 
> 
> e.g.: "chr22_KI270879v1_alt is not found in chromosome sizes file"
> 
> 

For what I remember, it should use `Refgenie` to get the chromosome sizes file. And verify the genome assembly of the input BEB file. If the input BED file is not verified with `Refgenie`, it should just skip the step to make the bigBed file. 

Can you send me the file you had problem with? I can test to make sure.

**Comment by xuebingjie1990** [comment]
> By executing bedmaker to convert bed to bigBed with unusual (not standard) chromosomes program can't find size of not standard chromosome in chromosome sizes file.
> 
> e.g.: "chr22_KI270879v1_alt is not found in chromosome sizes file"

I add a try/except block. So now it will print a message but the pipeline will not fail.  

It still works the same way as before; because it's using the `alias` to get the chrom.sizes file via `Refgenie`, the input file genome assembly (for example hg38) might not be the same genome assembly with that alias (hg38) in `Refgenie`.   In that case, there is no bigBed file generated. It shouldn't affect the downstream pipelines, but in the database, the `genome` and  `bigbed_files` fields would be empty.

**Comment by khoroshevskyi** [comment]
> > By executing bedmaker to convert bed to bigBed with unusual (not standard) chromosomes program can't find size of not standard chromosome in chromosome sizes file.
> > e.g.: "chr22_KI270879v1_alt is not found in chromosome sizes file"
> 
> I add a try/except block. So now it will print a message but the pipeline will not fail.
> 
> It still works the same way as before; because it's using the `alias` to get the chrom.sizes file via `Refgenie`, the input file genome assembly (for example hg38) might not be the same genome assembly with that alias (hg38) in `Refgenie`. In that case, there is no bigBed file generated. It shouldn't affect the downstream pipelines, but in the database, the `genome` and `bigbed_files` fields would be empty.

This change didn’t solve the issue. We should consider another solution e.g. deleting regions with not standard chromosome naming.
Also, the solution, where user have to create new chromosome sizes file is not efficient, as there could be hundreds of bed files that have to be converted.

**Comment by khoroshevskyi** [comment]
solved
