### ISSUE TITLE
pyBigWig for file type verification

### ISSUE THREAD

**Issue by stolarczyk** [databio/bed_maker#3]
[pyBigWig package](https://github.com/deeptools/pyBigWig) implements methods for file format assurance, i.e. `isBigWig()` or `.isBed()`. 

This might be useful in case we want to check the file type not only based on its extension. Or to verify if the conversion to BED format was successful. 

See: https://github.com/deeptools/pyBigWig#determining-the-file-type

**Comment by joseverdezoto** [comment]
@michalstolarczyk awesome, thanks for the heads up. I'll look into it. Also, the pipeline should be looper compatible now.

**Comment by joseverdezoto** [comment]
@michalstolarczyk maybe I'm missing something but it looks like the package can only tell us whether a file is in bigWig or bigBed format?. It could come handy in the pipeline script to check for bigWig files though.

Also, I was curious if there was something out there analogous to the readBed() function from LOLA, and came across this: https://github.com/maasha/biopieces/wiki/read_bed   

There's a switch that apparently lets you check the integrity of BED entries, so it might be worth to keep in the back of our minds.

**Comment by stolarczyk** [comment]
> It could come handy in the pipeline script to check for bigWig files though.

Well, it does -- as you mention in the previous sentence 😄 Or did you mean bedGraph format here?
