### ISSUE TITLE
bigWig to Bed conversion issues. 

### ISSUE THREAD

**Issue by joseverdezoto** [databio/bed_maker#4]
As of now, BEDmaker can be submitted to looper to convert bedGraph and bigBed files. However, the current way of piping **bigWigToBedgraph** and **macs2** produces an empty file.

I'll see if **bigWigToBedgraph** can output to stdout. Bottom line is that it'd be better not having to deal with intermediate bedGraph files.

**Comment by stolarczyk** [comment]
This is how you do it:
```
./bigWigToBedGraph file.bw stdout
```

**Comment by joseverdezoto** [comment]
Need to fix issue with piping implementation:

**bigWigToBedGraph** GSE99378_A17_V7.bw   /dev/stdout | **macs2**   bdgpeakcall -i /dev/stdout -o GSE99378_A17_V7.bed
