### ISSUE TITLE
wig to bed conversions

### ISSUE THREAD

**Issue by joseverdezoto** [databio/bed_maker#5]
@michalstolarczyk I just realized that I also have several data sources with wig files. If we decided to implement this conversion into the pipeline, I think there are 2 possible ways we could do it:

We could perhaps use the **wigToBigWig** tool and pipe stdout to our current BW to bed conversion template.
**Or**
I came across a command line executable that might do the trick, though haven't tested thoroughly yet: https://bedops.readthedocs.io/en/latest/content/reference/file-management/conversion/wig2bed.html

**Comment by stolarczyk** [comment]
Sure, let's implement it if you found some wig-formatted data. 

I think we should go for the first option. Since wig format is used for storage of continuous data we'd need to use a peak caller to get the bed-formatted regions of interest.
