### ISSUE TITLE
pipeline testing with wig files 

### ISSUE THREAD

**Issue by joseverdezoto** [databio/bed_maker#6]
@michalstolarczyk could you test the pipeline with some wig files? 

I'm still having some issues  handling that type of files. I don't think this has to do with the code. Looks like for some reason my test files don't match the information of the **chrom_sizes** files grabbed by the pipeline.

**Comment by stolarczyk** [comment]
I did not collect any wig files. I just have bigBed, bigWig and bedGraph.

If you still want me to look at it, just point me to a wig file of yours!

**Comment by joseverdezoto** [comment]
Thanks! I can show you the path to my hg19 wig files on Rivanna. It would be as follows:
 **/project/shefflab/resources/regions/LOLAHema/hg19/AML_ChiPseq_wig**

This is the sort of error I've been getting when submitting wig files to the pipeline:
**line 6472372 of GSM1513832_MV411_H3K4me3.wig: chromosome chrM has 16571 bases, but item ends at 16600**

I double checked I had the right reference genome. I'm wondering if there's maybe a variant of the hg19 chrom_sizes file.

**Comment by stolarczyk** [comment]
yeah, it's clearly a chrom.sizes compatibility issue which causes `wigToBigWig` to fail

in the `wigToBigWig` help it says:

> If the assembly <db> is hosted by UCSC, chrom.sizes can be a URL like http://hgdownload.soe.ucsc.edu/goldenPath/<db>/bigZips/<db>.chrom.sizes

so I went ahead and grabbed the file of interest and ran the command using this one and I got the same error:

```
[mjs5kd@udc-ba36-36 example](master): wget https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.chrom.sizes
--2019-12-04 12:07:44--  https://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/hg19.chrom.sizes
Resolving hgdownload.soe.ucsc.edu (hgdownload.soe.ucsc.edu)... 128.114.119.163
Connecting to hgdownload.soe.ucsc.edu (hgdownload.soe.ucsc.edu)|128.114.119.163|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1971 (1.9K) [text/plain]
Saving to: ‘hg19.chrom.sizes’

100%[================================================================================================================================================================>] 1,971       --.-K/s   in 0s      

2019-12-04 12:07:44 (120 MB/s) - ‘hg19.chrom.sizes’ saved [1971/1971]
[mjs5kd@udc-ba36-36 example](master): wigToBigWig files/GSM1513833_MV411_R_H3K4me3.wig hg19.chrom.sizes out.bw
line 4614196 of files/GSM1513833_MV411_R_H3K4me3.wig: chromosome chrM has 16571 bases, but item ends at 16600
[mjs5kd@udc-ba36-36 example](master): wigToBigWig files/GSM1513833_MV411_R_H3K4me3.wig /project/shefflab/genomes/hg19/fasta/default/hg19.chrom.sizes out.bw
line 4614196 of files/GSM1513833_MV411_R_H3K4me3.wig: chromosome chrM has 16571 bases, but item ends at 16600
```

no wonder -- the files are exactly the same

```
[mjs5kd@udc-ba36-36 example](master): diff /project/shefflab/genomes/hg19/fasta/default/hg19.chrom.sizes hg19.chrom.sizes 
[mjs5kd@udc-ba36-36 example](master): 
```

**Comment by nsheff** [comment]
the chrom.sizes file is not the problem. the file in question is what is in error; it does indeed extend past the end of chrM:

GSM1513833
```
fixedStep chrom=chrM start=13501 step=100 span=100
0.40
0.40
1.35
2.29
2.70
2.70
1.35
0.94
0.40
0.40
0.94
1.35
1.75
1.75
1.35
1.35
1.75
1.35
1.35
1.75
2.29
2.29
1.75
2.29
2.29
1.75
2.70
3.10
3.10
1.75
1.35
0.94
```
it may have something to do with their processing; they started in hg18 and lifted to hg38...somewhere something got messed up on the way. if you delete the 0.94 you could go past that, but that's annoying.

**Comment by nsheff** [comment]
@joseverdezoto can you close out this issue and leave a note as to how you solved it?

**Comment by joseverdezoto** [comment]
It seems that a lot of wig files (even from different sources) have this same issue. To get past it, we just have to pass a `-clip` flag along with the other arguments required by `wigToBigWig`:

`wigToBigWig  input.wig  chrom.sizes  output.bw  -clip`

This will raise a warning message for the troublesome lines, but won't stop the conversion as it did previously. The pipeline should have no problem getting the output into BED format.

**Comment by joseverdezoto** [comment]
It seems that a lot of wig files (even from different sources) have this same issue. To get past it, we just have to pass a `-clip` flag along with the other arguments required by `wigToBigWig`:

`wigToBigWig  input.wig  chrom.sizes  output.bw  -clip`

This will raise a warning message for the troublesome lines, but won't stop the conversion as it did previously. The pipeline should have no problem getting the output into BED format.

**Comment by joseverdezoto** [comment]
It seems that a lot of wig files (even from different sources) have this same issue. To get past it, we just have to pass a `-clip` flag along with the other arguments required by `wigToBigWig`:

`wigToBigWig  input.wig  chrom.sizes  output.bw  -clip`

This will raise a warning message for the troublesome lines, but won't stop the conversion as it did previously. The pipeline should have no problem getting the output into BED format.
